### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by aliou** [aliou/scratch.vim#3]
- [ ] `:Scratch` => Opens scratch / tmp file
- [ ] `:Scratch ft` => Opens scratch / tmp file and sets filetype to `ft` (e.g. `:Scratch sql`)

---

- [ ] Disable text width.
- [ ] Disable window height update (always keep to 10)
- [ ] Disable swap, backups, etc.

---

- [ ] Paste visual selection if any
- [ ] Set filetype to filetype of current file by default. (As an option?)
